# Generated by Django 5.2.12 on 2026-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(db_index=True, default='default', max_length=40, verbose_name='Phiên chat'),
        ),
    ]
