# Generated by Django 5.2 on 2026-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_chatmessage_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestion',
            name='type',
            field=models.CharField(choices=[('spending_alert', 'Cảnh báo chi tiêu'), ('saving_tip', 'Mẹo tiết kiệm'), ('goal_progress', 'Tiến độ mục tiêu'), ('budget_advice', 'Tư vấn ngân sách'), ('category_insight', 'Phân tích danh mục'), ('anomaly_detect', 'Chi tiêu bất thường'), ('income_boost', 'Cải thiện thu nhập'), ('smart_saving', 'Tiết kiệm thông minh')], max_length=30, verbose_name='Loại'),
        ),
    ]
