# Generated by Django 5.2 on 2026-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_aisuggestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestion',
            name='type',
            field=models.CharField(choices=[('spending_alert', 'Cảnh báo chi tiêu'), ('saving_tip', 'Mẹo tiết kiệm'), ('goal_progress', 'Tiến độ mục tiêu'), ('budget_advice', 'Tư vấn ngân sách'), ('category_insight', 'Phân tích danh mục'), ('anomaly_detect', 'Chi tiêu bất thường'), ('income_boost', 'Cải thiện thu nhập'), ('smart_saving', 'Tiết kiệm thông minh'), ('recurring_expense', 'Chi phí lặp lại'), ('budget_optimization', 'Tối ưu hóa ngân sách'), ('savings_milestone', 'Kỉ niệm tiết kiệm'), ('spending_pattern', 'Mô hình chi tiêu'), ('category_trend', 'Xu hướng danh mục')], max_length=30, verbose_name='Loại'),
        ),
    ]
