# Generated by Django 5.2 on 2026-04-12 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_goal_linked_budget_goal_is_auto_update_goaltransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi')),
                ('question_count', models.IntegerField(default=1, verbose_name='Số lần hỏi')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Danh mục')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Đánh dấu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giám sát hội thoại AI',
                'verbose_name_plural': 'Giám sát hội thoại AI',
                'ordering': ['-question_count'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên cấu hình')),
                ('tone', models.CharField(choices=[('strict', 'Khắt khe'), ('balanced', 'Cân bằng'), ('encouraging', 'Động viên'), ('friendly', 'Thân thiện')], default='balanced', max_length=20, verbose_name='Tính cách')),
                ('system_prompt', models.TextField(verbose_name='System Prompt')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=False, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Prompt AI',
                'verbose_name_plural': 'Cấu hình Prompt AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('finance_tips', 'Mẹo tài chính'), ('tax_rules', 'Quy định thuế'), ('saving_strategies', 'Chiến lược tiết kiệm'), ('investment_guide', 'Hướng dẫn đầu tư'), ('budget_tips', 'Mẹo lập ngân sách'), ('other', 'Khác')], max_length=30, verbose_name='Danh mục')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Từ khóa (cách nhau bằng dấu phẩy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dữ liệu huấn luyện AI',
                'verbose_name_plural': 'Dữ liệu huấn luyện AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('export', 'Xuất dữ liệu'), ('import', 'Nhập dữ liệu'), ('other', 'Khác')], max_length=20, verbose_name='Hành động')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên định mức')),
                ('threshold_percentage', models.IntegerField(default=80, verbose_name='Ngưỡng (%)')),
                ('alert_type', models.CharField(max_length=50, verbose_name='Loại cảnh báo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Định mức cảnh báo',
                'verbose_name_plural': 'Định mức cảnh báo',
                'ordering': ['threshold_percentage'],
            },
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], max_length=10, verbose_name='Loại')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon (emoji)')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Màu sắc (hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục mẫu',
                'verbose_name_plural': 'Danh mục mẫu',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Mã tiền tệ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tiền tệ')),
                ('symbol', models.CharField(max_length=10, verbose_name='Ký hiệu')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='Tỷ giá (so với VND)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tiền tệ',
                'verbose_name_plural': 'Tiền tệ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserAccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('suspended', 'Tạm khóa'), ('banned', 'Cấm'), ('inactive', 'Không hoạt động')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do')),
                ('suspended_until', models.DateTimeField(blank=True, null=True, verbose_name='Tạm khóa đến')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trạng thái tài khoản',
                'verbose_name_plural': 'Trạng thái tài khoản',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày')),
                ('total_users', models.IntegerField(default=0, verbose_name='Tổng người dùng')),
                ('active_users', models.IntegerField(default=0, verbose_name='Người dùng hoạt động')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Tổng giao dịch')),
                ('total_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng thu nhập')),
                ('total_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng chi tiêu')),
                ('avg_budget_per_user', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Ngân sách trung bình/người')),
                ('popular_categories', models.TextField(blank=True, null=True, verbose_name='Danh mục phổ biến')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Phân tích người dùng',
                'verbose_name_plural': 'Phân tích người dùng',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='goaltransaction',
            name='unique_goal_transaction',
        ),
        migrations.AlterUniqueTogether(
            name='goaltransaction',
            unique_together={('goal', 'transaction')},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='useraccountstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_status', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='finance_aud_user_id_145cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='finance_aud_action_0093f5_idx'),
        ),
    ]
