# Generated by Django 5.2 on 2026-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_aiconversationmonitor_aipromptconfig_aitrainingdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='icon',
            field=models.CharField(blank=True, default='🎯', max_length=50, verbose_name='Icon'),
        ),
    ]
