# Generated by Django 6.0.4 on 2026-04-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_goal_icon'),
        ('finance', '0008_remove_auto_update'),
    ]

    operations = [
    ]
